/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_qiuyu_testhellojni_MyJni */

#ifndef _Included_com_example_qiuyu_testhellojni_MyJni
#define _Included_com_example_qiuyu_testhellojni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeSetup
        (JNIEnv *, jobject);

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeExec
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeStaitcExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeStaitcExec
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeGetMyJniFieldN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeGetMyJniFieldN
        (JNIEnv *, jobject);

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeSetN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeSetN
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeGetN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeGetN
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
