///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class com_example_qiuyu_testhellojni_MyJni */
//
//#ifndef _Included_com_example_qiuyu_testhellojni_MyJni
//#define _Included_com_example_qiuyu_testhellojni_MyJni
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     com_example_qiuyu_testhellojni_MyJni
// * Method:    add
// * Signature: (II)I
// */
//JNIEXPORT jint JNICALL Java_com_example_qiuyu_testhellojni_MyJni_add
//  (JNIEnv * env, jobject obj, jint a, jint b) {
//    return a+b;
//  }
//
//#ifdef __cplusplus
//}
//#endif
//#endif
/* DO NOT EDIT THIS FILE - it is machine generated */

#include "com_example_qiuyu_testhellojni_MyJni.h"

jclass m_class;
jobject m_object;
jmethodID m_getValue, m_getV;

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeSetup
* Signature: ()V
*/
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeSetup
        (JNIEnv *env, jobject thiz) {
    jclass clazz = (*env)->GetObjectClass(env, thiz);
    m_class = (jclass)(*env)->NewGlobalRef(env,clazz);
    m_object = (jobject)(*env)->NewGlobalRef(env,thiz);
    m_getV = (*env)->GetMethodID(env,m_class,"getvalue2","(I)V");
    m_getValue = (*env)->GetStaticMethodID(env,m_class,"getvalue1", "(I)V");
    return;
}

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeExec
        (JNIEnv *env, jobject thiz, jint value) {
    (*env)->CallStaticVoidMethod(env,m_class,m_getValue,value);
    (*env)->CallVoidMethod(env,m_object,m_getV,value);
    return;
}

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeStaitcExec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeStaitcExec
        (JNIEnv *env, jclass clasz, jint value) {
    (*env)->CallStaticVoidMethod(env,m_class,m_getValue,value);
    (*env)->CallVoidMethod(env,m_object,m_getV,value);
    return;
}

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeGetMyJniFieldN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeGetMyJniFieldN
        (JNIEnv * env, jobject thiz) {
    jclass clazz = (*env)->GetObjectClass(env, thiz);
    //jfieldID    (*GetFieldID)(JNIEnv*, jclass, const char*, const char*);
    jfieldID myjni_n = (*env)->GetFieldID(env, clazz, "n", "I");
    //jobject     (*GetObjectField)(JNIEnv*, jobject, jfieldID);
    return (*env)->GetIntField(env, thiz, myjni_n);
}

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeSetN
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeSetN
        (JNIEnv * env, jobject thiz, jint n) {
    jclass clazz = (*env)->GetObjectClass(env, thiz);
    jmethodID setN = (*env)->GetMethodID(env,clazz,"setN","(I)V");
    (*env)->CallVoidMethod(env,thiz,setN,n);
}

/*
 * Class:     com_example_qiuyu_testhellojni_MyJni
 * Method:    nativeGetN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_qiuyu_testhellojni_MyJni_nativeGetN
        (JNIEnv * env, jobject thiz) {
    jclass clazz = (*env)->GetObjectClass(env, thiz);
    jmethodID getN = (*env)->GetMethodID(env,clazz,"getN","()I");
    return (*env)->CallIntMethod(env,thiz,getN);
}


